DOMAIN = "wg_easy"
DEFAULT_POLL_INTERVAL = 30
DEFAULT_ONLINE_TIMEOUT_MINUTES = 5  # legacy, kept only for one-time migration
DEFAULT_ONLINE_TIMEOUT_SECONDS = 300
CONF_ONLINE_TIMEOUT_MINUTES = "online_timeout_minutes"  # legacy option key
CONF_ONLINE_TIMEOUT_SECONDS = "online_timeout_seconds"
PLATFORMS = ["sensor", "binary_sensor"]
SERVER_DEVICE_ID = "wireguard_server"
ENTITY_ID_PREFIX = "wg"
